# Generated by Django 3.2.15 on 2023-09-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatGptConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("get_skin_type", models.TextField(blank=True, default="")),
                ("get_skin_improvement", models.TextField(blank=True, default="")),
                ("choose_product", models.TextField(blank=True, default="")),
                ("product_recommendations", models.TextField(blank=True, default="")),
                ("get_skincare_routine", models.TextField(blank=True, default="")),
                ("healthy_recipes", models.TextField(blank=True, default="")),
                ("stress_management", models.TextField(blank=True, default="")),
                ("sleep_management", models.TextField(blank=True, default="")),
                ("activity_improvement", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "ChatGpt Configuration",
            },
        ),
    ]
