# Generated by Django 3.2.15 on 2024-02-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_gpt", "0002_usermessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermessage",
            name="category",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="usermessage",
            name="category_updated",
            field=models.BooleanField(default=False),
        ),
    ]
