# Generated by Django 3.2.4 on 2021-07-08 09:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "routine_type",
                    models.CharField(
                        choices=[("AM", "AM"), ("PM", "PM")], max_length=30
                    ),
                ),
                ("make_up_cleaned", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MorningQuestionnaire",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feeling_today",
                    models.CharField(
                        choices=[
                            ("BAD", "BAD"),
                            ("MEHHH", "MEHHH"),
                            ("WELL", "WELL"),
                            ("LOVE_IT", "LOVE_IT"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "hours_of_sleep",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(14),
                        ]
                    ),
                ),
                (
                    "sleep_quality",
                    models.CharField(
                        choices=[
                            ("BAD", "BAD"),
                            ("MEHHH", "MEHHH"),
                            ("WELL", "WELL"),
                            ("LOVE_IT", "LOVE_IT"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "something_special",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MENSTRUATION", "MENSTRUATION"),
                            ("SHAVING", "SHAVING"),
                            ("VACATION", "VACATION"),
                            ("MEET_DR", "MEET_DR"),
                            ("START_DRUG_TREATMENT", "START_DRUG_TREATMENT"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="morning_questionnaires",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EveningQuestionnaire",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skin_feel",
                    models.CharField(
                        choices=[
                            ("SENSITIVE", "SENSITIVE"),
                            ("GREASY", "GREASY"),
                            ("DEHYDRATED", "DEHYDRATED"),
                            ("NORMAL", "NORMAL"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "diet_today",
                    models.CharField(
                        choices=[
                            ("BALANCED", "BALANCED"),
                            ("MILDLY", "MILDLY_BALANCED"),
                            ("UNBALANCED", "UNBALANCED"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "water",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3),
                        ]
                    ),
                ),
                (
                    "life_happened",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COFFEE_JUNKIE", "COFFEE"),
                            ("BOOZE_EXPERT", "ALCOHOL"),
                            ("JUNK_FOOD_&_SWEETS", "JUNK_FOOD_AND_SWEETS"),
                            ("SMOKING", "SMOKING"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "stress_levels",
                    models.CharField(
                        choices=[
                            ("EXTREME", "EXTREME"),
                            ("MODERATE", "MODERATE"),
                            ("RELAXED", "RELAXED"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "exercise_hours",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(8),
                        ]
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evening_questionnaires",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
