# Generated by Django 3.2.6 on 2021-08-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0002_facescan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routine",
            name="make_up_cleaned",
        ),
    ]
