# Generated by Django 3.2.6 on 2021-09-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0003_remove_routine_make_up_cleaned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eveningquestionnaire",
            name="diet_today",
            field=models.CharField(
                choices=[
                    ("BALANCED", "BALANCED"),
                    ("MILDLY_BALANCED", "MILDLY_BALANCED"),
                    ("UNBALANCED", "UNBALANCED"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="eveningquestionnaire",
            name="life_happened",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COFFEE", "COFFEE"),
                    ("ALCOHOL", "ALCOHOL"),
                    ("JUNK_FOOD_AND_SWEETS", "JUNK_FOOD_AND_SWEETS"),
                    ("SMOKING", "SMOKING"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
