# Generated by Django 3.2.6 on 2021-11-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0004_auto_20210928_0742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eveningquestionnaire",
            name="exercise_hours",
            field=models.CharField(
                choices=[
                    ("0", "ZERO"),
                    ("1", "ONE"),
                    ("2", "TWO"),
                    ("3", "THREE"),
                    ("4", "FOUR"),
                    ("5", "FIVE"),
                    ("6", "SIX"),
                    ("7", "SEVEN"),
                    ("8", "EIGHT"),
                ],
                max_length=30,
            ),
        ),
    ]
