# Generated by Django 3.2.12 on 2022-03-22 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0007_auto_20220321_0933"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceScanSmoothingAnalytics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acne", models.PositiveIntegerField(default=0)),
                ("lines", models.PositiveIntegerField(default=0)),
                ("wrinkles", models.PositiveIntegerField(default=0)),
                ("pigmentation", models.PositiveIntegerField(default=0)),
                ("translucency", models.PositiveIntegerField(default=0)),
                ("quality", models.PositiveIntegerField(default=0)),
                ("eye_bags", models.PositiveIntegerField(default=0)),
                ("pores", models.PositiveIntegerField(default=0)),
                ("sagging", models.PositiveIntegerField(default=0)),
                ("uniformness", models.PositiveIntegerField(default=0)),
                ("hydration", models.PositiveIntegerField(default=0)),
                ("redness", models.PositiveIntegerField(default=0)),
                ("raw_data", models.JSONField()),
                (
                    "face_scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smoothing_analytics",
                        to="routines.facescan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FaceScanAnalytics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acne", models.PositiveIntegerField(default=0)),
                ("lines", models.PositiveIntegerField(default=0)),
                ("wrinkles", models.PositiveIntegerField(default=0)),
                ("pigmentation", models.PositiveIntegerField(default=0)),
                ("translucency", models.PositiveIntegerField(default=0)),
                ("quality", models.PositiveIntegerField(default=0)),
                ("eye_bags", models.PositiveIntegerField(default=0)),
                ("pores", models.PositiveIntegerField(default=0)),
                ("sagging", models.PositiveIntegerField(default=0)),
                ("uniformness", models.PositiveIntegerField(default=0)),
                ("hydration", models.PositiveIntegerField(default=0)),
                ("redness", models.PositiveIntegerField(default=0)),
                ("raw_data", models.JSONField()),
                (
                    "face_scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="routines.facescan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
