# Generated by Django 3.2.12 on 2022-03-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0008_facescananalytics_facescansmoothinganalytics"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facescananalytics",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="facescansmoothinganalytics",
            options={"ordering": ["-created_at"]},
        ),
    ]
