# Generated by Django 3.2.12 on 2022-04-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0009_auto_20220323_0919"),
    ]

    operations = [
        migrations.AddField(
            model_name="facescananalytics",
            name="is_valid",
            field=models.BooleanField(default=True),
        ),
    ]
