# Generated by Django 3.2.12 on 2022-04-11 13:27

from django.db import migrations


def set_is_valid(apps, schema_editor):
    FaceScanAnalytics = apps.get_model("routines", "FaceScanAnalytics")
    records = []
    for f_scan_analytic in FaceScanAnalytics.objects.all():
        f_scan_analytic.is_valid = bool(f_scan_analytic.raw_data[0]["is_ok"])
        records.append(f_scan_analytic)
    FaceScanAnalytics.objects.bulk_update(records, ["is_valid"])


class Migration(migrations.Migration):
    dependencies = [
        ("routines", "0010_facescananalytics_is_valid"),
    ]

    operations = [migrations.RunPython(set_is_valid)]
