# Generated by Django 3.2.13 on 2022-05-17 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_auto_20220517_1156"),
        ("routines", "0013_auto_20220512_1304"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceScanComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comment_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_scan_comment_templates",
                        to="home.facescancommenttemplate",
                    ),
                ),
                (
                    "face_scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_scan_comments",
                        to="routines.facescan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
