# Generated by Django 3.2.13 on 2022-06-01 06:58

import apps.routines
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("routines", "0015_auto_20220520_0925"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="tag name.", max_length=100)),
                ("slug", models.SlugField(editable=False, max_length=128)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SKIN_CARE", "SKIN_CARE"),
                            ("WELL_BEING", "WELL_BEING"),
                            ("NUTRITION", "NUTRITION"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="dailyquestionnaire",
            name="tags_for_nutrition",
            field=models.ManyToManyField(
                limit_choices_to={"category": apps.routines.TagCategories["NUTRITION"]},
                related_name="nutrition_tags",
                to="routines.UserTag",
            ),
        ),
        migrations.AddField(
            model_name="dailyquestionnaire",
            name="tags_for_skin_care",
            field=models.ManyToManyField(
                limit_choices_to={"category": apps.routines.TagCategories["SKIN_CARE"]},
                related_name="skincare_tags",
                to="routines.UserTag",
            ),
        ),
        migrations.AddField(
            model_name="dailyquestionnaire",
            name="tags_for_well_being",
            field=models.ManyToManyField(
                limit_choices_to={
                    "category": apps.routines.TagCategories["WELL_BEING"]
                },
                related_name="wellbeing_tags",
                to="routines.UserTag",
            ),
        ),
        migrations.AddConstraint(
            model_name="usertag",
            constraint=models.UniqueConstraint(
                fields=("user", "slug", "category"),
                name="One tag per user per category",
            ),
        ),
        migrations.AddConstraint(
            model_name="usertag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("slug", "category"),
                name="One predefined tag per category",
            ),
        ),
    ]
