# Generated by Django 3.2.13 on 2022-06-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0018_auto_20220606_1857"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcareevent",
            name="is_reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="healthcareevent",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True, help_text="reminder sent at", null=True
            ),
        ),
    ]
