# Generated by Django 3.2.13 on 2022-06-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0019_auto_20220610_0640"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyquestionnaire",
            options={"ordering": ["-created_at"]},
        ),
    ]
