# Generated by Django 3.2.13 on 2022-07-18 13:36

import apps.routines
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0020_alter_dailyquestionnaire_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcareevent",
            name="event_tags",
            field=models.ManyToManyField(
                limit_choices_to={
                    "category__in": [
                        apps.routines.TagCategories["MEDICATION"],
                        apps.routines.TagCategories["APPOINTMENT"],
                        apps.routines.TagCategories["MENSTRUATION"],
                    ]
                },
                related_name="health_care_event_tags",
                to="routines.UserTag",
            ),
        ),
        migrations.AlterField(
            model_name="usertag",
            name="category",
            field=models.CharField(
                choices=[
                    ("SKIN_CARE", "SKIN_CARE"),
                    ("WELL_BEING", "WELL_BEING"),
                    ("NUTRITION", "NUTRITION"),
                    ("MEDICATION", "MEDICATION"),
                    ("APPOINTMENT", "APPOINTMENT"),
                    ("MENSTRUATION", "MENSTRUATION"),
                ],
                max_length=30,
            ),
        ),
    ]
