# Generated by Django 3.2.15 on 2022-08-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0021_auto_20220718_1336"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcareevent",
            name="remind_me",
            field=models.BooleanField(default=True),
        ),
    ]
