# Generated by Django 3.2.15 on 2022-08-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0022_healthcareevent_remind_me"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="healthcareevent",
            options={"ordering": ["-start_date"]},
        ),
    ]
