# Generated by Django 3.2.15 on 2022-08-17 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("monetization", "0001_initial"),
        ("routines", "0024_auto_20220816_1338"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatisticsPurchase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store_name",
                    models.CharField(
                        choices=[
                            ("APP_STORE", "APP_STORE"),
                            ("PLAY_STORE", "PLAY_STORE"),
                        ],
                        default="APP_STORE",
                        max_length=100,
                    ),
                ),
                (
                    "receipt_data",
                    models.TextField(
                        blank=True, default="", help_text="Appstore receipt data"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="subscription purchase order or transaction id",
                        max_length=200,
                    ),
                ),
                (
                    "purchase_started_on",
                    models.DateTimeField(
                        blank=True, help_text="purchase started on date time", null=True
                    ),
                ),
                (
                    "purchase_ends_after",
                    models.DateTimeField(
                        blank=True, help_text="purchase ends after date time", null=True
                    ),
                ),
                (
                    "total_transactions",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="total subscription transactions",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "STARTED"),
                            ("CANCELED", "CANCELED"),
                            ("COMPLETED", "COMPLETED"),
                            ("PAUSED", "PAUSED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="STARTED",
                        max_length=100,
                    ),
                ),
                (
                    "store_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="monetization.storeproduct",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchased_statistics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
