# Generated by Django 3.2.15 on 2022-09-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0025_statisticspurchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyquestionnaire",
            name="sleep_quality",
            field=models.CharField(
                choices=[
                    ("LOVE_IT", "LOVE_IT"),
                    ("WELL", "WELL"),
                    ("MEHHH", "MEHHH"),
                    ("BAD", "BAD"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="dailyquestionnaire",
            name="stress_levels",
            field=models.CharField(
                choices=[
                    ("RELAXED", "RELAXED"),
                    ("MODERATE", "MODERATE"),
                    ("EXTREME", "EXTREME"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="eveningquestionnaire",
            name="stress_levels",
            field=models.CharField(
                choices=[
                    ("RELAXED", "RELAXED"),
                    ("MODERATE", "MODERATE"),
                    ("EXTREME", "EXTREME"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="morningquestionnaire",
            name="sleep_quality",
            field=models.CharField(
                choices=[
                    ("LOVE_IT", "LOVE_IT"),
                    ("WELL", "WELL"),
                    ("MEHHH", "MEHHH"),
                    ("BAD", "BAD"),
                ],
                max_length=30,
            ),
        ),
    ]
