# Generated by Django 3.2.15 on 2022-09-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0027_auto_20220908_1144"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statisticspurchase",
            options={"ordering": ["-created_at"]},
        ),
    ]
