# Generated by Django 3.2.15 on 2022-09-15 12:01

from django.db import migrations, models
import uuid


def set_statistics_purchase_uuid(apps, schema_editor):
    StatisticsPurchase = apps.get_model("routines", "StatisticsPurchase")
    for purchase in StatisticsPurchase.objects.all():
        purchase.uuid = uuid.uuid4()
        purchase.save()


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0028_alter_statisticspurchase_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="statisticspurchase",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(set_statistics_purchase_uuid, migrations.RunPython.noop),
    ]
