# Generated by Django 3.2.15 on 2022-09-15 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0029_statisticspurchase_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statisticspurchase",
            name="id",
        ),
        migrations.AlterField(
            model_name="statisticspurchase",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
