# Generated by Django 3.2.15 on 2022-09-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0030_auto_20220915_1203"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statisticspurchase",
            old_name="uuid",
            new_name="id",
        ),
    ]
