# Generated by Django 3.2.15 on 2022-09-29 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0031_rename_uuid_statisticspurchase_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "STARTED"),
                            ("CANCELED", "CANCELED"),
                            ("COMPLETED", "COMPLETED"),
                            ("PAUSED", "PAUSED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="STARTED",
                        max_length=50,
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routines.statisticspurchase",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Purchase History",
            },
        ),
    ]
