# Generated by Django 3.2.15 on 2023-02-23 11:11

from django.conf import settings
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("routines", "0032_purchasehistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyProductGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.CharField(max_length=255)),
                (
                    "email",
                    django.contrib.postgres.fields.citext.CIEmailField(
                        blank=True, max_length=255
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_group",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DailyProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(blank=True, default="", upload_to="products"),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("brand", models.CharField(blank=True, max_length=255)),
                ("ingredients", models.CharField(blank=True, max_length=255)),
                ("size", models.CharField(blank=True, max_length=30)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CLEANSER", "CLEANSER"),
                            ("MOISTURIZER", "MOISTURIZER"),
                            ("TREATMENT", "TREATMENT"),
                        ],
                        max_length=11,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="routines.dailyproductgroup",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="dailyproduct",
            constraint=models.UniqueConstraint(
                fields=("group", "type"), name="One group per type"
            ),
        ),
    ]
