# Generated by Django 3.2.15 on 2023-02-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0034_remove_dailyproductgroup_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyproductgroup",
            name="age",
        ),
    ]
