# Generated by Django 3.2.15 on 2023-04-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0035_remove_dailyproductgroup_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyProductTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("ingredients", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
