# Generated by Django 3.2.15 on 2023-05-12 11:23

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("routines", "0038_scrapedproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ACNE", "ACNE"),
                            ("PIGMENTATION", "PIGMENTATION"),
                            ("UNIFORMNESS", "UNIFORMNESS"),
                            ("HYDRATION", "HYDRATION"),
                            ("PORES", "PORES"),
                            ("REDNESS", "REDNESS"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "previuos_indexes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("current_index", models.PositiveIntegerField(null=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.UniqueConstraint(
                fields=("user", "category"), name="One category per user"
            ),
        ),
    ]
