# Generated by Django 3.2.15 on 2023-05-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0039_auto_20230512_1123"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyproduct",
            name="is_medication",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scrapedproduct",
            name="is_medication",
            field=models.BooleanField(default=False),
        ),
    ]
