# Generated by Django 3.2.15 on 2023-07-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0040_auto_20230515_0817"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyproduct",
            name="product_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="routines.scrapedproduct",
            ),
        ),
        migrations.AlterField(
            model_name="scrapedproduct",
            name="brand",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="scrapedproduct",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="scrapedproduct",
            name="ingredients",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="scrapedproduct",
            name="status_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scrapedproduct",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="scrapedproduct",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
