# Generated by Django 3.2.15 on 2023-07-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0041_auto_20230710_1432"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyproduct",
            name="product_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="routines.scrapedproduct",
            ),
        ),
    ]
