# Generated by Django 3.2.15 on 2023-07-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0042_alter_dailyproduct_product_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapedproduct",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
