# Generated by Django 3.2.15 on 2023-08-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0043_alter_scrapedproduct_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyproduct",
            name="image_parse_fail",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
