# Generated by Django 3.2.15 on 2023-09-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0045_dailyproduct_connect_scrapped_fail"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyproduct",
            name="review_score",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
