# Generated by Django 3.2.15 on 2023-09-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0046_dailyproduct_review_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyproduct",
            name="brand_updated",
            field=models.BooleanField(default=False),
        ),
    ]
