# Generated by Django 3.2.15 on 2023-10-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0047_dailyproduct_brand_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyproduct",
            name="accessibility_score",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="dailyproduct",
            name="cost_score",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="dailyproduct",
            name="efficiency_score",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="dailyproduct",
            name="preference_score",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="dailyproduct",
            name="satisfaction_score",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
