# Generated by Django 3.2.15 on 2023-11-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0051_facescan_updated_sagging"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyproduct",
            name="easy_to_use_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
