# Generated by Django 3.2.15 on 2023-11-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0052_dailyproduct_easy_to_use_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapedproduct",
            name="source",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
