# Generated by Django 3.2.15 on 2023-11-27 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("routines", "0053_scrapedproduct_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapedproduct",
            name="image",
            field=models.ImageField(
                blank=True, default="", upload_to="scraped_products"
            ),
        ),
        migrations.CreateModel(
            name="UserScrapedProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("want", models.BooleanField(default=False)),
                ("have", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="routines.scrapedproduct",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="scrapedproduct",
            name="users",
            field=models.ManyToManyField(
                related_name="products",
                through="routines.UserScrapedProduct",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
