# Generated by Django 3.2.15 on 2023-11-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0056_rename_be_aware_scrapedproduct_side_effects"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scrapedproduct",
            old_name="good_for",
            new_name="positive_effects",
        ),
    ]
