# Generated by Django 3.2.4 on 2021-07-02 08:18

import ckeditor.fields
import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("translations", "0003_alter_translation_language"),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Technical name.", max_length=255, unique=True
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("TEXT", "TEXT"), ("VIDEO", "VIDEO")], max_length=10
                    ),
                ),
                ("thumbnail", models.ImageField(upload_to="thumbnails")),
                ("video", models.FileField(blank=True, default="", upload_to="videos")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Technical name.", max_length=255, unique=True
                    ),
                ),
                ("image", models.ImageField(upload_to="category_images")),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="CategoryTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="content.category",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        default="en",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="translations.language",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("headline", models.CharField(max_length=255)),
                ("main_text", ckeditor.fields.RichTextField(blank=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="content.article",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        default="en",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="translations.language",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="content.category",
            ),
        ),
        migrations.AddIndex(
            model_name="categorytranslation",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="content_cat_title_0f4421_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="categorytranslation",
            constraint=models.UniqueConstraint(
                fields=("language", "category"), name="One language per category"
            ),
        ),
        migrations.AddIndex(
            model_name="articletranslation",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="content_art_title_1a8a5c_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="articletranslation",
            constraint=models.UniqueConstraint(
                fields=("language", "article"), name="One language per article"
            ),
        ),
    ]
