# Generated by Django 3.2.4 on 2021-07-28 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0003_auto_20210713_1420"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="period",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="content.period",
            ),
        ),
        migrations.CreateModel(
            name="UserArticle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_users",
                        to="content.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_questionnaire_variable",
                    models.CharField(
                        choices=[
                            ("SKIN_GOAL", "SKIN_GOAL"),
                            ("FEELING_TODAY", "FEELING_TODAY"),
                            ("AGE", "AGE"),
                            ("GENDER", "GENDER"),
                            ("CONTRACEPTIVE_PILL", "CONTRACEPTIVE_PILL"),
                            ("MENSTRUATING_PERSON", "MENSTRUATING_PERSON"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "comparison_operator",
                    models.CharField(
                        choices=[
                            ("IS_GREATER_THAN", "IS_GREATER_THAN"),
                            ("IS_EQUAL_TO", "IS_EQUAL_TO"),
                            ("IS_LESS_THAN", "IS_LESS_THAN"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("LESS_PIMPLES", "LESS_PIMPLES"),
                            ("LESS_SCARS", "LESS_SCARS"),
                            ("LESS_WRINKLES", "LESS_WRINKLES"),
                            ("OVERALL_SKIN_HEALTH", "OVERALL_SKIN_HEALTH"),
                            ("AGE_12_16", "AGE_12_16"),
                            ("AGE_17_21", "AGE_17_21"),
                            ("AGE_22_26", "AGE_22_26"),
                            ("AGE_27_31", "AGE_27_31"),
                            ("AGE_32_36", "AGE_32_36"),
                            ("AGE_37_41", "AGE_37_41"),
                            ("AGE_42_46", "AGE_42_46"),
                            ("AGE_47_51", "AGE_47_51"),
                            ("AGE_52_56", "AGE_52_56"),
                            ("AGE_57_61", "AGE_57_61"),
                            ("AGE_61_PLUS", "AGE_61_PLUS"),
                            ("FEMALE", "FEMALE"),
                            ("DIVERSE", "DIVERSE"),
                            ("MALE", "MALE"),
                            ("BAD", "BAD"),
                            ("MEHHH", "MEHHH"),
                            ("WELL", "WELL"),
                            ("LOVE_IT", "LOVE_IT"),
                            ("ON_BIRTH_CONTROL", "ON_BIRTH_CONTROL"),
                            ("STOPPED_BIRTH_CONTROL", "STOPPED_BIRTH_CONTROL"),
                            ("NEVER_BEEN_ON_IT", "NEVER_BEEN_ON_IT"),
                            ("IM_PREGNANT", "IM_PREGNANT"),
                            ("True", "TRUE"),
                            ("False", "FALSE"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="content.article",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="article",
            name="users",
            field=models.ManyToManyField(
                related_name="articles",
                through="content.UserArticle",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="userarticle",
            constraint=models.UniqueConstraint(
                fields=("article", "user"), name="One user per article"
            ),
        ),
    ]
