# Generated by Django 3.2.6 on 2021-08-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_auto_20210802_1534"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
