# Generated by Django 3.2.6 on 2021-08-05 14:16

import apps.content.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_article_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="video_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="video",
            field=models.FileField(
                blank=True,
                default="",
                upload_to="videos",
                validators=[
                    django.core.validators.FileExtensionValidator(["mp4"]),
                    apps.content.validators.validate_size,
                ],
            ),
        ),
    ]
