# Generated by Django 3.2.6 on 2021-08-19 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_auto_20210805_1416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="unlocks_after_week",
            field=models.IntegerField(
                help_text="Number of a week after which the period unlocks - 0 to 6",
                unique=True,
                validators=[
                    django.core.validators.MaxValueValidator(6),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
