# Generated by Django 3.2.6 on 2021-08-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_alter_period_unlocks_after_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="unlocks_after_week",
            field=models.IntegerField(
                help_text="Number of a week after which the period unlocks", unique=True
            ),
        ),
    ]
