# Generated by Django 3.2.6 on 2021-09-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_alter_period_unlocks_after_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorytranslation",
            name="description",
            field=models.TextField(),
        ),
    ]
