# Generated by Django 3.2.6 on 2021-10-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_alter_categorytranslation_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("CORE_PROGRAM", "CORE_PROGRAM"),
                    ("SKIN_STORIES", "SKIN_STORIES"),
                    ("SKIN_SCHOOL", "SKIN_SCHOOL"),
                    ("RECIPES", "RECIPES"),
                ],
                max_length=30,
            ),
        ),
    ]
