# Generated by Django 3.2.6 on 2021-11-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="article_image",
            field=models.ImageField(blank=True, default="", upload_to="article_images"),
        ),
    ]
