# Generated by Django 3.2.12 on 2022-04-19 07:05

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0003_alter_translation_language"),
        ("content", "0014_auto_20220221_0934"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("NUTRITION", "NUTRITION"),
                            ("BREAKFAST", "BREAKFAST"),
                            ("LUNCH", "LUNCH"),
                            ("DINNER", "DINNER"),
                            ("SNACKS", "SNACKS"),
                        ],
                        max_length=30,
                    ),
                ),
                ("image", models.ImageField(upload_to="subcategory_images")),
            ],
            options={
                "verbose_name_plural": "Subcategories",
            },
        ),
        migrations.CreateModel(
            name="SubCategoryTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                (
                    "language",
                    models.ForeignKey(
                        default="en",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="translations.language",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="content.subcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="article",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="content.subcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="subcategorytranslation",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="content_sub_title_acde7b_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="subcategorytranslation",
            constraint=models.UniqueConstraint(
                fields=("language", "subcategory"), name="One language per subcategory"
            ),
        ),
    ]
