# Generated by Django 3.2.12 on 2022-04-21 06:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_auto_20220420_0731"),
    ]

    operations = [
        migrations.AddField(
            model_name="articletranslation",
            name="sub_headline",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="articletranslation",
            name="headline",
            field=models.TextField(),
        ),
    ]
