# Generated by Django 3.2.12 on 2022-04-26 04:00
import datetime

from django.db import migrations

from apps.content import CategoryName


def update_initial_article(apps, schema_editor):
    records = []
    UserArticle = apps.get_model("content", "UserArticle")
    today = datetime.datetime.now(datetime.timezone.utc)
    for init_article in UserArticle.objects.filter(
        article__category__name=CategoryName.INITIAL,
        user__questionnaire__created_at__lte=(today - datetime.timedelta(days=7)),
    ):
        init_article.is_read = True
        init_article.read_at = init_article.user.questionnaire.created_at
        records.append(init_article)
    UserArticle.objects.bulk_update(records, ["is_read", "read_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0017_auto_20220421_0642"),
        # Dependency for UserArticle data migration
        (
            "questionnaire",
            "0012_rename_guilty_pleasures_array_userquestionnaire_guilty_pleasures",
        ),
    ]

    operations = [
        migrations.RunPython(update_initial_article, migrations.RunPython.noop)
    ]
