# Generated by Django 3.2.15 on 2022-11-04 09:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0019_article_lifestyle_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articletranslation",
            name="main_text",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
