# Generated by Django 3.2.15 on 2023-01-11 13:13

from django.db import migrations, models
import django.db.models.deletion


def update_subcategories(apps, schema_editor):
    Category = apps.get_model("content", "Category")
    SubCategory = apps.get_model("content", "SubCategory")

    category_subcategory_names = {
        "CORE_PROGRAM": ["HABITS", "SKINCARE", "WELLBEING", "NUTRITIONS"],
        "RECIPES": ["NUTRITION", "BREAKFAST", "LUNCH", "DINNER", "SNACKS"],
    }

    for category_name, subcategories_names in category_subcategory_names.items():
        if category := Category.objects.filter(name=category_name).first():
            if category.name == "RECIPES":
                SubCategory.objects.filter(name__in=subcategories_names).update(
                    category=category
                )
            elif category.name == "CORE_PROGRAM":
                SubCategory.objects.bulk_create(
                    [
                        SubCategory(name=name, category=category)
                        for name in subcategories_names
                    ]
                )


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0020_alter_articletranslation_main_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="content.category",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(
                choices=[
                    ("NUTRITION", "NUTRITION"),
                    ("BREAKFAST", "BREAKFAST"),
                    ("LUNCH", "LUNCH"),
                    ("DINNER", "DINNER"),
                    ("SNACKS", "SNACKS"),
                    ("HABITS", "HABITS"),
                    ("SKINCARE", "SKINCARE"),
                    ("WELLBEING", "WELLBEING"),
                    ("NUTRITIONS", "NUTRITIONS"),
                ],
                max_length=30,
            ),
        ),
        migrations.RunPython(
            update_subcategories, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="content.category",
            ),
        ),
    ]
