# Generated by Django 3.2.15 on 2023-01-26 11:52

from django.db import migrations, models


def update_subcategories(apps, schema_editor):
    SubCategory = apps.get_model("content", "SubCategory")
    SubCategory.objects.filter(name="NUTRITION").update(name="RECIPE_NUTRITION")


def reverse_subcategories(apps, schema_editor):
    SubCategory = apps.get_model("content", "SubCategory")
    SubCategory.objects.filter(name="RECIPE_NUTRITION").update(name="NUTRITION")


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0021_auto_20230111_1313"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(
                choices=[
                    ("RECIPE_NUTRITION", "RECIPE_NUTRITION"),
                    ("BREAKFAST", "BREAKFAST"),
                    ("LUNCH", "LUNCH"),
                    ("DINNER", "DINNER"),
                    ("SNACKS", "SNACKS"),
                    ("HABITS", "HABITS"),
                    ("SKINCARE", "SKINCARE"),
                    ("WELLBEING", "WELLBEING"),
                    ("NUTRITIONS", "NUTRITIONS"),
                ],
                max_length=30,
            ),
        ),
        migrations.RunPython(update_subcategories, reverse_code=reverse_subcategories),
    ]
