# Generated by Django 3.2.15 on 2023-03-09 14:56

from django.db import migrations, models


def update_subcategories(apps, schema_editor):
    Category = apps.get_model("content", "Category")
    SubCategory = apps.get_model("content", "SubCategory")

    category_subcategory_names = {
        "INDIAN_RECIPES": [
            "INDIAN_BREAKFAST",
            "INDIAN_LUNCH",
            "INDIAN_DINNER",
            "INDIAN_SNACK",
        ],
        "INDIAN_ARTICLES": [],
    }

    for category_name, subcategory_names in category_subcategory_names.items():
        category = Category.objects.create(name=category_name)
        if subcategory_names:
            SubCategory.objects.bulk_create(
                [
                    SubCategory(name=name, category=category)
                    for name in subcategory_names
                ]
            )


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0022_alter_subcategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("CORE_PROGRAM", "CORE_PROGRAM"),
                    ("SKIN_STORIES", "SKIN_STORIES"),
                    ("SKIN_SCHOOL", "SKIN_SCHOOL"),
                    ("RECIPES", "RECIPES"),
                    ("INITIAL", "INITIAL"),
                    ("INDIAN_RECIPES", "INDIAN_RECIPES"),
                    ("INDIAN_ARTICLES", "INDIAN_ARTICLES"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(
                choices=[
                    ("RECIPE_NUTRITION", "RECIPE_NUTRITION"),
                    ("BREAKFAST", "BREAKFAST"),
                    ("LUNCH", "LUNCH"),
                    ("DINNER", "DINNER"),
                    ("SNACKS", "SNACKS"),
                    ("HABITS", "HABITS"),
                    ("SKINCARE", "SKINCARE"),
                    ("WELLBEING", "WELLBEING"),
                    ("NUTRITIONS", "NUTRITIONS"),
                    ("INDIAN_BREAKFAST", "INDIAN_BREAKFAST"),
                    ("INDIAN_LUNCH", "INDIAN_LUNCH"),
                    ("INDIAN_DINNER", "INDIAN_DINNER"),
                    ("INDIAN_SNACK", "INDIAN_SNACK"),
                ],
                max_length=30,
            ),
        ),
        migrations.RunPython(
            update_subcategories, reverse_code=migrations.RunPython.noop
        ),
    ]
