# Generated by Django 3.2.4 on 2021-06-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="app_version_latest",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="app_version_minimal_supported",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
