# Generated by Django 3.2.6 on 2021-08-18 14:32

import ckeditor.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0003_alter_translation_language"),
        ("home", "0005_auto_20210730_0858"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkinJourney",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Technical name.", max_length=255, unique=True
                    ),
                ),
                ("image", models.ImageField(upload_to="skin_journey_images")),
            ],
            options={
                "verbose_name_plural": "Skin Journey",
            },
        ),
        migrations.CreateModel(
            name="SkinJourneyTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "language",
                    models.ForeignKey(
                        default="en",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="translations.language",
                    ),
                ),
                (
                    "skin_journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="home.skinjourney",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="skin_journey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skin_journey",
                to="home.skinjourney",
            ),
        ),
        migrations.AddIndex(
            model_name="skinjourneytranslation",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="home_skinjo_title_143179_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="skinjourneytranslation",
            constraint=models.UniqueConstraint(
                fields=("language", "skin_journey"),
                name="One language per skin_journey",
            ),
        ),
    ]
