# Generated by Django 3.2.6 on 2021-10-04 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_auto_20210819_0715"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dashboardorder",
            old_name="progress",
            new_name="recipes",
        ),
    ]
