# Generated by Django 3.2.12 on 2022-04-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_auto_20220415_0505"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardelementtranslation",
            name="content",
            field=models.TextField(),
        ),
    ]
