# Generated by Django 3.2.12 on 2022-04-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_dashboardelementtranslation_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="scan_duration",
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
