# Generated by Django 3.2.12 on 2022-04-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_siteconfiguration_scan_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="scan_duration",
            field=models.PositiveSmallIntegerField(
                default=3, help_text="Face scan duration in days"
            ),
        ),
    ]
