# Generated by Django 3.2.13 on 2022-05-17 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0003_alter_translation_language"),
        ("home", "0012_alter_siteconfiguration_scan_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceScanCommentTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FaceScanCommentTemplateTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "language",
                    models.ForeignKey(
                        default="en",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="translations.language",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_scan_comment_translations",
                        to="home.facescancommenttemplate",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="facescancommenttemplatetranslation",
            constraint=models.UniqueConstraint(
                fields=("template", "language"),
                name="One comment template per language",
            ),
        ),
    ]
