# Generated by Django 3.2.13 on 2022-06-13 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_alter_predictiontemplate_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="appointment_reminder_notification_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment_reminder_notification_template",
                to="home.notificationtemplate",
            ),
        ),
    ]
