# Generated by Django 3.2.13 on 2022-06-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "home",
            "0018_siteconfiguration_daily_questionnaire_reminder_notification_template",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="predictiontemplatetranslation",
            name="image",
            field=models.ImageField(
                blank=True, default="", upload_to="prediction_images"
            ),
        ),
    ]
