# Generated by Django 3.2.13 on 2022-07-08 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_predictiontemplatetranslation_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictiontemplatetranslation",
            name="image",
            field=models.FileField(
                blank=True,
                default="",
                upload_to="prediction_images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "jpg",
                            "jpeg",
                            "png",
                            "svg",
                            "bmp",
                            "gif",
                            "webp",
                            "psd",
                            "tiff",
                        ]
                    )
                ],
            ),
        ),
    ]
