# Generated by Django 3.2.15 on 2022-09-07 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_alter_predictiontemplatetranslation_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="monthly_statistics_notification_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monthly_statistics_notification_template",
                to="home.notificationtemplate",
            ),
        ),
    ]
