# Generated by Django 3.2.15 on 2022-09-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_siteconfiguration_monthly_statistics_notification_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="payments_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
