# Generated by Django 3.2.15 on 2022-10-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_siteconfiguration_payments_enabled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siteconfiguration",
            old_name="payments_enabled",
            new_name="android_payments_enabled",
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="ios_payments_enabled",
            field=models.BooleanField(
                default=False, verbose_name="IOS payments enabled"
            ),
        ),
    ]
