# Generated by Django 3.2.15 on 2022-11-21 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_about_and_notice_section(apps, schema_editor):
    AboutAndNoticeSection = apps.get_model("home", "AboutAndNoticeSection")
    for i, about_and_notice_section in enumerate(
        AboutAndNoticeSection.objects.all(), 1
    ):
        about_and_notice_section.version = i
        about_and_notice_section.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0023_auto_20221010_1212"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAcceptedAboutAndNoticeSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="aboutandnoticesection",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TERMS_OF_SERVICE", "TERMS_OF_SERVICE"),
                    ("PRIVACY_POLICY", "PRIVACY_POLICY"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="aboutandnoticesection",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(
            populate_about_and_notice_section, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="aboutandnoticesection",
            name="name",
            field=models.CharField(help_text="Technical name.", max_length=255),
        ),
        migrations.AddConstraint(
            model_name="aboutandnoticesection",
            constraint=models.UniqueConstraint(
                fields=("type", "version"), name="One version per type"
            ),
        ),
        migrations.AddConstraint(
            model_name="aboutandnoticesection",
            constraint=models.UniqueConstraint(
                fields=("name", "version"), name="Unique name per version"
            ),
        ),
        migrations.AddField(
            model_name="useracceptedaboutandnoticesection",
            name="about_and_notice_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_accepted_about_and_notice_section",
                to="home.aboutandnoticesection",
            ),
        ),
        migrations.AddField(
            model_name="useracceptedaboutandnoticesection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_accepted_about_and_notice_section",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="useracceptedaboutandnoticesection",
            constraint=models.UniqueConstraint(
                fields=("user", "about_and_notice_section"),
                name="One about_and_notice_section per user",
            ),
        ),
    ]
