# Generated by Django 3.2.15 on 2022-11-25 10:28

from django.db import migrations


def populate_user_about_and_notice_section(apps, schema_editor):
    AboutAndNoticeSection = apps.get_model("home", "AboutAndNoticeSection")
    User = apps.get_model("users", "User")
    UserAcceptedAboutAndNoticeSection = apps.get_model(
        "home", "UserAcceptedAboutAndNoticeSection"
    )

    about_and_notice_sections = AboutAndNoticeSection.objects.all()
    user_about_and_notice_sections = []

    for user in User.objects.all():
        for about_and_notice_section in about_and_notice_sections:
            user_about_and_notice_sections.append(
                UserAcceptedAboutAndNoticeSection(
                    user=user, about_and_notice_section=about_and_notice_section
                )
            )
    UserAcceptedAboutAndNoticeSection.objects.bulk_create(
        user_about_and_notice_sections
    )


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_auto_20221121_1434"),
    ]

    operations = [
        migrations.RunPython(
            populate_user_about_and_notice_section,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
