# Generated by Django 3.2.4 on 2021-07-08 15:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="",
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="user_avatars",
            ),
        ),
    ]
