# Generated by Django 3.2.4 on 2021-07-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_articles_read"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="articles_read",
        ),
    ]
