# Generated by Django 3.2.15 on 2023-03-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="device",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="geolocation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="operating_system",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
