# Generated by Django 3.2.15 on 2023-04-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20230328_1119"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_amplitude_synced",
            field=models.BooleanField(default=False),
        ),
    ]
