# Generated by Django 3.2.15 on 2023-07-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_is_amplitude_synced"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="health_data",
            field=models.BooleanField(default=False),
        ),
    ]
