# Generated by Django 3.2.15 on 2023-07-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_health_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_gpt_history",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
