# Generated by Django 3.2.15 on 2023-08-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_chat_gpt_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="chat_gpt_history",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
