# Generated by Django 2.2.3 on 2019-07-09 15:52
from django.conf import settings
from django.db import migrations


def create_default_lang(apps, schema_editor):
    Language = apps.get_model("translations", "Language")
    Language.objects.get_or_create(
        code=settings.DEFAULT_LANGUAGE,
        defaults={"name": settings.TRANSLATIONS_BASE_LANGUAGE[1]},
    )


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_lang),
    ]
