# Generated by Django 3.2.13 on 2022-07-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=55, unique=True)),
                ("description", models.CharField(max_length=200)),
                (
                    "sku",
                    models.CharField(
                        help_text="Stock Keeping Unit - alphanumeric identifier from stores",
                        max_length=154,
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
