# Generated by Django 3.2.15 on 2022-09-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monetization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeproduct",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
