# Generated by Django 3.2.15 on 2022-09-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monetization", "0002_storeproduct_is_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeproduct",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
