# Generated by Django 3.2.4 on 2021-06-22 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuestionnaire",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "skin_goal",
                    models.CharField(
                        choices=[
                            ("LESS_PIMPLES", "LESS_PIMPLES"),
                            ("LESS_SCARS", "LESS_SCARS"),
                            ("LESS_WRINKLES", "LESS_WRINKLES"),
                            ("OVERALL_SKIN_HEALTH", "OVERALL_SKIN_HEALTH"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "feeling_today",
                    models.CharField(
                        choices=[
                            ("BAD", "BAD"),
                            ("MEHHH", "MEHHH"),
                            ("WELL", "WELL"),
                            ("LOVE_IT", "LOVE_IT"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("12-16_YEARS", "AGE_12_16"),
                            ("17-21_YEARS", "AGE_17_21"),
                            ("22-26_YEARS", "AGE_22_26"),
                            ("27-31_YEARS", "AGE_27_31"),
                            ("32-36_YEARS", "AGE_32_36"),
                            ("37-41_YEARS", "AGE_37_41"),
                            ("42-46_YEARS", "AGE_42_46"),
                            ("47-51_YEARS", "AGE_47_51"),
                            ("52-56_YEARS", "AGE_52_56"),
                            ("57-61_YEARS", "AGE_57_61"),
                            ("61+_YEARS", "AGE_61_PLUS"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("FEMALE", "FEMALE"),
                            ("DIVERSE", "DIVERSE"),
                            ("MALE", "MALE"),
                        ],
                        max_length=30,
                    ),
                ),
                ("female_power_date", models.DateField(blank=True, null=True)),
                (
                    "contraceptive_pill",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ON_BIRTH_CONTROL", "ON_BIRTH_CONTROL"),
                            ("STOPPED_BIRTH_CONTROL", "STOPPED_BIRTH_CONTROL"),
                            ("NEVER_BEEN_ON_IT", "NEVER_BEEN_ON_IT"),
                            ("IM_PREGNANT", "PREGNANT"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("stopped_birth_control_date", models.DateField(blank=True, null=True)),
                ("menstruating_person", models.BooleanField(blank=True, null=True)),
                (
                    "skin_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OILY_SKIN", "OILY_SKIN"),
                            ("NORMAL_SKIN", "NORMAL_SKIN"),
                            ("COMBINATION_SKIN", "COMBINATION_SKIN"),
                            ("DRY_SKIN", "DRY_SKIN"),
                            ("SKIPPED", "SKIPPED"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "skin_feel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SENSITIVE", "SENSITIVE"),
                            ("GREASY", "GREASY"),
                            ("DEHYDRATED", "DEHYDRATED"),
                            ("NORMAL", "NORMAL"),
                            ("SKIPPED", "SKIPPED"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "expectations",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ASAP", "ASAP"),
                            ("AFTER_TWO_WEEKS", "AFTER_TWO_WEEKS"),
                            ("IT_TAKES_TIME", "IT_TAKES_TIME"),
                            ("SKIPPED", "SKIPPED"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "diet_balance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BALANCED", "BALANCED"),
                            ("MILDLY_BALANCED", "MILDLY_BALANCED"),
                            ("UNBALANCED", "UNBALANCED"),
                            ("SKIPPED", "SKIPPED"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "diet",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VEGAN/VEGETARIAN", "VEGAN_VEGETARIAN"),
                            ("DIARY_FREE", "DIARY_FREE"),
                            ("MIXED_(EVERYTHING)", "MIXED"),
                            ("LOW_CARB", "LOW_CARB"),
                            ("SKIPPED", "SKIPPED"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "guilty_pleasures",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COFFEE_JUNKIE", "COFFEE"),
                            ("ALCOHOL", "ALCOHOL"),
                            ("JUNK_FOOD_&_SWEETS", "JUNK_FOOD_AND_SWEETS"),
                            ("SMOKING", "SMOKING"),
                            ("SKIPPED", "SKIPPED"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "easily_stressed",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YES", "YES"),
                            ("MODERATE", "MODERATE"),
                            ("NO", "NO"),
                            ("SKIPPED", "SKIPPED"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "hours_of_sleep",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "ONE"),
                            ("2", "TWO"),
                            ("3", "THREE"),
                            ("4", "FOUR"),
                            ("5", "FIVE"),
                            ("6", "SIX"),
                            ("7", "SEVEN"),
                            ("8", "EIGHT"),
                            ("9", "NINE"),
                            ("10", "TEN"),
                            ("11", "ELEVEN"),
                            ("12", "TWELVE"),
                            ("13", "THIRTEEN"),
                            ("14", "FOURTEEN"),
                            ("SKIPPED", "SKIPPED"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "exercise_days_a_week",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "ONE"),
                            ("2", "TWO"),
                            ("3", "THREE"),
                            ("4", "FOUR"),
                            ("5", "FIVE"),
                            ("6", "SIX"),
                            ("7", "SEVEN"),
                            ("SKIPPED", "SKIPPED"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questionnaire",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
