# Generated by Django 3.2.4 on 2021-06-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userquestionnaire",
            name="contraceptive_pill",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ON_BIRTH_CONTROL", "ON_BIRTH_CONTROL"),
                    ("STOPPED_BIRTH_CONTROL", "STOPPED_BIRTH_CONTROL"),
                    ("NEVER_BEEN_ON_IT", "NEVER_BEEN_ON_IT"),
                    ("IM_PREGNANT", "PREGNANT"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userquestionnaire",
            name="diet",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VEGAN/VEGETARIAN", "VEGAN_VEGETARIAN"),
                    ("DIARY_FREE", "DIARY_FREE"),
                    ("MIXED_(EVERYTHING)", "MIXED"),
                    ("LOW_CARB", "LOW_CARB"),
                    ("SKIPPED", "SKIPPED"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userquestionnaire",
            name="diet_balance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BALANCED", "BALANCED"),
                    ("MILDLY_BALANCED", "MILDLY_BALANCED"),
                    ("UNBALANCED", "UNBALANCED"),
                    ("SKIPPED", "SKIPPED"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userquestionnaire",
            name="easily_stressed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("YES", "YES"),
                    ("MODERATE", "MODERATE"),
                    ("NO", "NO"),
                    ("SKIPPED", "SKIPPED"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userquestionnaire",
            name="exercise_days_a_week",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "ONE"),
                    ("2", "TWO"),
                    ("3", "THREE"),
                    ("4", "FOUR"),
                    ("5", "FIVE"),
                    ("6", "SIX"),
                    ("7", "SEVEN"),
                    ("SKIPPED", "SKIPPED"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userquestionnaire",
            name="expectations",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ASAP", "ASAP"),
                    ("AFTER_TWO_WEEKS", "AFTER_TWO_WEEKS"),
                    ("IT_TAKES_TIME", "IT_TAKES_TIME"),
                    ("SKIPPED", "SKIPPED"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userquestionnaire",
            name="guilty_pleasures",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COFFEE_JUNKIE", "COFFEE"),
                    ("ALCOHOL", "ALCOHOL"),
                    ("JUNK_FOOD_&_SWEETS", "JUNK_FOOD_AND_SWEETS"),
                    ("SMOKING", "SMOKING"),
                    ("SKIPPED", "SKIPPED"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userquestionnaire",
            name="hours_of_sleep",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "ONE"),
                    ("2", "TWO"),
                    ("3", "THREE"),
                    ("4", "FOUR"),
                    ("5", "FIVE"),
                    ("6", "SIX"),
                    ("7", "SEVEN"),
                    ("8", "EIGHT"),
                    ("9", "NINE"),
                    ("10", "TEN"),
                    ("11", "ELEVEN"),
                    ("12", "TWELVE"),
                    ("13", "THIRTEEN"),
                    ("14", "FOURTEEN"),
                    ("SKIPPED", "SKIPPED"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userquestionnaire",
            name="skin_feel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SENSITIVE", "SENSITIVE"),
                    ("GREASY", "GREASY"),
                    ("DEHYDRATED", "DEHYDRATED"),
                    ("NORMAL", "NORMAL"),
                    ("SKIPPED", "SKIPPED"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userquestionnaire",
            name="skin_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OILY_SKIN", "OILY_SKIN"),
                    ("NORMAL_SKIN", "NORMAL_SKIN"),
                    ("COMBINATION_SKIN", "COMBINATION_SKIN"),
                    ("DRY_SKIN", "DRY_SKIN"),
                    ("SKIPPED", "SKIPPED"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
