# Generated by Django 3.2.4 on 2021-07-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0002_auto_20210623_0900"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestionnaire",
            name="make_up",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
