# Generated by Django 3.2.4 on 2021-07-09 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0003_userquestionnaire_make_up"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userquestionnaire",
            name="id",
        ),
        migrations.AlterField(
            model_name="userquestionnaire",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
