# Generated by Django 3.2.4 on 2021-07-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0004_auto_20210709_1033"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userquestionnaire",
            old_name="uuid",
            new_name="id",
        ),
    ]
