# Generated by Django 3.2.4 on 2021-07-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0005_rename_uuid_userquestionnaire_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userquestionnaire",
            name="age",
            field=models.CharField(
                choices=[
                    ("AGE_12_16", "AGE_12_16"),
                    ("AGE_17_21", "AGE_17_21"),
                    ("AGE_22_26", "AGE_22_26"),
                    ("AGE_27_31", "AGE_27_31"),
                    ("AGE_32_36", "AGE_32_36"),
                    ("AGE_37_41", "AGE_37_41"),
                    ("AGE_42_46", "AGE_42_46"),
                    ("AGE_47_51", "AGE_47_51"),
                    ("AGE_52_56", "AGE_52_56"),
                    ("AGE_57_61", "AGE_57_61"),
                    ("AGE_61_PLUS", "AGE_61_PLUS"),
                ],
                max_length=30,
            ),
        ),
    ]
