# Generated by Django 3.2.4 on 2021-07-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0006_alter_userquestionnaire_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userquestionnaire",
            name="contraceptive_pill",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ON_BIRTH_CONTROL", "ON_BIRTH_CONTROL"),
                    ("STOPPED_BIRTH_CONTROL", "STOPPED_BIRTH_CONTROL"),
                    ("NEVER_BEEN_ON_IT", "NEVER_BEEN_ON_IT"),
                    ("IM_PREGNANT", "IM_PREGNANT"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
