# Generated by Django 3.2.6 on 2021-09-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0007_alter_userquestionnaire_contraceptive_pill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userquestionnaire",
            name="diet",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VEGAN_VEGETARIAN", "VEGAN_VEGETARIAN"),
                    ("DIARY_FREE", "DIARY_FREE"),
                    ("MIXED", "MIXED"),
                    ("LOW_CARB", "LOW_CARB"),
                    ("SKIPPED", "SKIPPED"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userquestionnaire",
            name="guilty_pleasures",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COFFEE", "COFFEE"),
                    ("ALCOHOL", "ALCOHOL"),
                    ("JUNK_FOOD_AND_SWEETS", "JUNK_FOOD_AND_SWEETS"),
                    ("SMOKING", "SMOKING"),
                    ("SKIPPED", "SKIPPED"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
