# Generated by Django 3.2.6 on 2021-11-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0010_userquestionnaire_guilty_pleasures_array"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userquestionnaire",
            name="guilty_pleasures",
        ),
    ]
