# Generated by Django 3.2.6 on 2021-11-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0011_remove_userquestionnaire_guilty_pleasures"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userquestionnaire",
            old_name="guilty_pleasures_array",
            new_name="guilty_pleasures",
        ),
    ]
