# Generated by Django 3.2.13 on 2022-05-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questionnaire",
            "0012_rename_guilty_pleasures_array_userquestionnaire_guilty_pleasures",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestionnaire",
            name="smoking_preferences",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HABITUAL_SMOKER", "HABITUAL_SMOKER"),
                    ("SOCIAL_SMOKER", "SOCIAL_SMOKER"),
                    ("ANXIOUS_SMOKER", "ANXIOUS_SMOKER"),
                    ("NON_SMOKER", "NON_SMOKER"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
