# Generated by Django 3.2.15 on 2022-10-13 09:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0013_userquestionnaire_smoking_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestionnaire",
            name="is_logging_menstruation",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userquestionnaire",
            name="exercise_days_a_week",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ZERO", "ZERO"),
                    ("ONE", "ONE"),
                    ("TWO", "TWO"),
                    ("THREE", "THREE"),
                    ("FOUR", "FOUR"),
                    ("FIVE", "FIVE"),
                    ("SIX_PLUS", "SIX_PLUS"),
                    ("SKIPPED", "SKIPPED"),
                    ("EVERY_DAY", "EVERY_DAY"),
                    ("FOUR_FIVE", "FOUR_FIVE"),
                    ("ONE_THREE", "ONE_THREE"),
                    ("NO_EXERCISE", "NO_EXERCISE"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userquestionnaire",
            name="guilty_pleasures",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("COFFEE", "COFFEE"),
                        ("ALCOHOL", "ALCOHOL"),
                        ("JUNK_FOOD_AND_SWEETS", "JUNK_FOOD_AND_SWEETS"),
                        ("SMOKING", "SMOKING"),
                        ("SKIPPED", "SKIPPED"),
                        ("IM_INNOCENT", "IM_INNOCENT"),
                    ],
                    max_length=30,
                ),
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="userquestionnaire",
            name="hours_of_sleep",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "ONE"),
                    ("2", "TWO"),
                    ("3", "THREE"),
                    ("4", "FOUR"),
                    ("5", "FIVE"),
                    ("6", "SIX"),
                    ("7", "SEVEN"),
                    ("8", "EIGHT"),
                    ("9", "NINE"),
                    ("10", "TEN"),
                    ("11", "ELEVEN"),
                    ("12", "TWELVE"),
                    ("13", "THIRTEEN"),
                    ("14", "FOURTEEN"),
                    ("SKIPPED", "SKIPPED"),
                    ("NINE_PLUS", "NINE_PLUS"),
                    ("SEVEN_EIGHT", "SEVEN_EIGHT"),
                    ("FIVE_SIX", "FIVE_SIX"),
                    ("ZERO_FOUR", "ZERO_FOUR"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
