# Generated by Django 3.2.15 on 2023-04-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0014_auto_20221013_0950"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestionnaire",
            name="availability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STUDYING", "STUDYING"),
                    ("WORKING_FULL_TIME", "WORKING_FULL_TIME"),
                    ("WORKING_PART_TIME", "WORKING_PART_TIME"),
                    ("NOT_BUSY", "NOT_BUSY"),
                    ("MATERNITY_LEAVE", "MATERNITY_LEAVE"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
