# Generated by Django 3.2.15 on 2023-05-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0015_userquestionnaire_availability"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userquestionnaire",
            name="availability",
        ),
        migrations.AddField(
            model_name="userquestionnaire",
            name="daily_busyness",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STUDY", "STUDY"),
                    ("FULL_TIME", "FULL_TIME"),
                    ("PART_TIME", "PART_TIME"),
                    ("NOT_BUSY", "NOT_BUSY"),
                    ("MATERNITY", "MATERNITY"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
